export const Cities = [
	{ value: 'umuahia', label: 'Umuahia' },
	{ value: 'yola', label: 'Yola' },
	{ value: 'uyo', label: 'Uyo' },
	{ value: 'awka', label: 'Awka' },
	{ value: 'bauchi', label: 'Bauchi' },
	{ value: 'yenagoa', label: 'Yenagoa' },
	{ value: 'makurdi', label: 'Makurdi' },
	{ value: 'maiduguri', label: 'Maiduguri' },
	{ value: 'calabar', label: 'Calabar' },
	{ value: 'asaba', label: 'Asaba' },
	{ value: 'abakaliki', label: 'Abakaliki' },
	{ value: 'benin-city', label: 'Benin City' },
	{ value: 'ado-ekiti', label: 'Ado-Ekiti' },
	{ value: 'enugu', label: 'Enugu' },
	{ value: 'abuja', label: 'Abuja' },
	{ value: 'gombe', label: 'Gombe' },
	{ value: 'owerri', label: 'Owerri' },
	{ value: 'dutse', label: 'Dutse' },
	{ value: 'kaduna', label: 'Kaduna' },
	{ value: 'kano', label: 'Kano' },
	{ value: 'katsina', label: 'Katsina' },
	{ value: 'birnin-kebbi', label: 'Birnin Kebbi' },
	{ value: 'lokoja', label: 'Lokoja' },
	{ value: 'ilorin', label: 'Ilorin' },
	{ value: 'ikeja', label: 'Ikeja' },
	{ value: 'lafia', label: 'Lafia' },
	{ value: 'minna', label: 'Minna' },
	{ value: 'abeokuta', label: 'Abeokuta' },
	{ value: 'akure', label: 'Akure' },
	{ value: 'osogbo', label: 'Osogbo' },
	{ value: 'ibadan', label: 'Ibadan' },
	{ value: 'jos', label: 'Jos' },
	{ value: 'port-harcourt', label: 'Port Harcourt' },
	{ value: 'sokoto', label: 'Sokoto' },
	{ value: 'jalingo', label: 'Jalingo' },
	{ value: 'damaturu', label: 'Damaturu' },
	{ value: 'gusau', label: 'Gusau' },
];
